### ISSUE TITLE
When will Polyel support PHP 8?

### ISSUE THREAD

**Issue by necrogami** [Superbition/Polyel#1]
I was wondering when this and the framework were going to be available for PHP8?

**Comment by embluk** [comment]
Hello thanks for talking an interest in Polyel!

PHP 8 support is on the list, currently I am prioritising other work right now. However, I am scheduled to finish work on my other project next week! So that means I plan to spend all my free time on Polyel again, expect work to pick up with Polyel within the next few months, which should include official support for PHP 8.

You are also free to test Polyel with PHP 8 and report any issues you find 👍🏻
